spring.application.name=AI-RoadTrip-Planner

server.port=8081

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/ai_roadtrip_planner
spring.datasource.username=root

# TEMPORARY: put your real MySQL password here for testing
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# JWT
# ===============================

jwt.expiration=3600000


# ===============================
# OPENROUTE SERVICE
# ===============================

# TEMPORARY: put your real OpenRouteService API key here for testing
openroute.api.key=${OPENROUTE_API_KEY}
openroute.base-url=https://api.heigit.org/openrouteservice

openroute.profile=driving-car


# ===============================
# POI / FAMOUS PLACES
# ===============================

openroute.poi-url=https://api.heigit.org/openpoiservice/v0/pois


# ===============================
# GEMINI AI
# Keep this ready for next step
# ===============================

# gemini.api.key=YOUR_REAL_GEMINI_API_KEY
# gemini.model=gemini-2.5-flash
# gemini.base-url=https://generativelanguage.googleapis.com/v1beta